### ISSUE TITLE
请问文章可以发布为github文章吗？

### ISSUE THREAD

**Issue by JiangKui007** [88250/awesome-solo#2]
最近在迁移博客到CSDN，为什么我的文章从github中访问都是直接链接到博客里了。还有备份怎么没有更新？

**Comment by 88250** [comment]
GitHub 上的 solo-blog 仓库主要是起到一个索引和备份的作用；重新登录一下 Solo 同步备份应该就会恢复，如果超过一天还没恢复请继续反馈。
